@echo off
:: ============================================================
::  Warehouse Fitness — RFID Bridge Installer
::  Run this on the CLIENT'S PC as Administrator.
:: ============================================================
setlocal enabledelayedexpansion
title RFID Bridge — Installer

:: ── Must run as Admin ────────────────────────────────────────
net session >nul 2>&1
if errorlevel 1 (
    echo  [ERROR] Please right-click install.bat and choose "Run as administrator"
    pause & exit /b 1
)

echo.
echo  ============================================
echo   Warehouse Fitness RFID Bridge — Installer
echo  ============================================
echo.

set INSTALL_DIR=C:\RFIDBridge
set EXE_NAME=rfid_bridge.exe
set TASK_NAME=WarehouseFitness_RFIDBridge

:: ── Create install folder ────────────────────────────────────
echo  [1/5] Creating install folder: %INSTALL_DIR%
if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"

:: ── Copy files ───────────────────────────────────────────────
echo  [2/5] Copying files...
copy /y "%~dp0%EXE_NAME%"       "%INSTALL_DIR%\%EXE_NAME%"      >nul
copy /y "%~dp0.env.template"    "%INSTALL_DIR%\.env.template"   >nul
copy /y "%~dp0uninstall.bat"    "%INSTALL_DIR%\uninstall.bat"   >nul
echo  [OK] Files copied to %INSTALL_DIR%

:: ── Configure .env ───────────────────────────────────────────
echo.
echo  [3/5] Configuring .env file...
echo.

if exist "%INSTALL_DIR%\.env" (
    echo  [NOTICE] .env already exists — skipping to preserve your settings.
    echo           Edit %INSTALL_DIR%\.env manually if needed.
    goto :skip_env
)

:: Copy template as starting point
copy /y "%INSTALL_DIR%\.env.template" "%INSTALL_DIR%\.env" >nul

echo  Enter your configuration details:
echo  (Press Enter to keep the default value shown in brackets)
echo.

:: COM Port
set "DEFAULT_PORT=COM11"
set /p "COM_PORT=  ESP32 Serial Port [%DEFAULT_PORT%]: "
if "!COM_PORT!"=="" set COM_PORT=%DEFAULT_PORT%

:: Supabase URL
set /p "SUPA_URL=  Supabase URL (e.g. https://xxx.supabase.co): "

:: Supabase Key
set /p "SUPA_KEY=  Supabase Anon Key: "

:: Write .env
(
    echo # Warehouse Fitness RFID Bridge — auto-generated by installer
    echo SERIAL_PORT=!COM_PORT!
    echo BAUD_RATE=115200
    echo HTTP_PORT=8765
    echo SUPABASE_URL=!SUPA_URL!
    echo SUPABASE_KEY=!SUPA_KEY!
) > "%INSTALL_DIR%\.env"

echo.
echo  [OK] .env saved to %INSTALL_DIR%\.env

:skip_env

:: ── Register Windows Task Scheduler ──────────────────────────
echo.
echo  [4/5] Registering startup task in Task Scheduler...

:: Remove old task if exists
schtasks /delete /tn "%TASK_NAME%" /f >nul 2>&1

:: Create XML for the task
set XML_PATH=%TEMP%\rfid_task.xml
(
echo ^<?xml version="1.0" encoding="UTF-16"?^>
echo ^<Task version="1.3" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"^>
echo   ^<RegistrationInfo^>
echo     ^<Description^>Warehouse Fitness RFID Bridge Service^</Description^>
echo   ^</RegistrationInfo^>
echo   ^<Triggers^>
echo     ^<BootTrigger^>
echo       ^<Enabled^>true^</Enabled^>
echo       ^<Delay^>PT30S^</Delay^>
echo     ^</BootTrigger^>
echo   ^</Triggers^>
echo   ^<Principals^>
echo     ^<Principal id="Author"^>
echo       ^<LogonType^>InteractiveToken^</LogonType^>
echo       ^<RunLevel^>HighestAvailable^</RunLevel^>
echo     ^</Principal^>
echo   ^</Principals^>
echo   ^<Settings^>
echo     ^<MultipleInstancesPolicy^>IgnoreNew^</MultipleInstancesPolicy^>
echo     ^<DisallowStartIfOnBatteries^>false^</DisallowStartIfOnBatteries^>
echo     ^<StopIfGoingOnBatteries^>false^</StopIfGoingOnBatteries^>
echo     ^<ExecutionTimeLimit^>PT0S^</ExecutionTimeLimit^>
echo     ^<RestartOnFailure^>
echo       ^<Interval^>PT1M^</Interval^>
echo       ^<Count^>999^</Count^>
echo     ^</RestartOnFailure^>
echo   ^</Settings^>
echo   ^<Actions^>
echo     ^<Exec^>
echo       ^<Command^>%INSTALL_DIR%\%EXE_NAME%^</Command^>
echo       ^<WorkingDirectory^>%INSTALL_DIR%^</WorkingDirectory^>
echo     ^</Exec^>
echo   ^</Actions^>
echo ^</Task^>
) > "%XML_PATH%"

schtasks /create /tn "%TASK_NAME%" /xml "%XML_PATH%" /f >nul
if errorlevel 1 (
    echo  [ERROR] Failed to register Task Scheduler task.
    echo         You may need to start rfid_bridge.exe manually from %INSTALL_DIR%
) else (
    echo  [OK] Startup task registered: "%TASK_NAME%"
)
del "%XML_PATH%" >nul 2>&1

:: ── Start the bridge now ──────────────────────────────────────
echo.
echo  [5/5] Starting RFID Bridge now...
start "RFID Bridge" "%INSTALL_DIR%\%EXE_NAME%"
timeout /t 2 >nul

echo.
echo  ============================================
echo   INSTALLATION COMPLETE
echo.
echo   Install location : %INSTALL_DIR%
echo   Config file      : %INSTALL_DIR%\.env
echo   Log file         : %INSTALL_DIR%\rfid_bridge.log
echo   Auto-start       : On every Windows boot (30s delay)
echo.
echo   To uninstall: run %INSTALL_DIR%\uninstall.bat
echo  ============================================
echo.
pause
